Upgrade pip before installing packages
We tried to upgrade just jupyterhub and nbgitpuller package,
but this seems to be causing it to refuse to start:

```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 5, in <module>
    from jupyterhub.singleuser import main
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/singleuser/__init__.py", line 5, in <module>
    from .app import SingleUserNotebookApp, main
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/singleuser/app.py", line 15, in <module>
    from .mixins import make_singleuser_app
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/singleuser/mixins.py", line 44, in <module>
    from ..log import log_request
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/log.py", line 14, in <module>
    from .handlers.pages import HealthCheckHandler
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/handlers/__init__.py", line 1, in <module>
    from . import base, login, metrics, pages
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/handlers/base.py", line 24, in <module>
    from .. import __version__, orm, roles, scopes
  File "/opt/conda/lib/python3.7/site-packages/jupyterhub/orm.py", line 31, in <module>
    from sqlalchemy.orm import (
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/__init__.py", line 56, in <module>
    from .decl_api import add_mapped_attribute as add_mapped_attribute
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/orm/decl_api.py", line 164, in <module>
    query_expression,
TypeError: dataclass_transform() got an unexpected keyword argument
'field_specifiers'
```

Googling around, this looks like a version mismatch mostl likely,
caused by https://github.com/2i2c-org/2i2c-hubs-image/pull/4. It
pinned 'top level' packages but nothing more basic, so most likely
a dependent package (perhaps sqlalchemy) got fucked up.

Hopefully, newer version of pip will actually SAT solve a little
and get us better versions. Let's see.